(cl:defpackage spencer_tracking_msgs-msg
  (:use )
  (:export
   "<PERSONTRAJECTORY>"
   "PERSONTRAJECTORY"
   "<TRACKEDGROUPS>"
   "TRACKEDGROUPS"
   "<PERSONTRAJECTORYENTRY>"
   "PERSONTRAJECTORYENTRY"
   "<COMPOSITEDETECTEDPERSON>"
   "COMPOSITEDETECTEDPERSON"
   "<TRACKEDGROUP>"
   "TRACKEDGROUP"
   "<COMPOSITEDETECTEDPERSONS>"
   "COMPOSITEDETECTEDPERSONS"
   "<TRACKEDPERSON>"
   "TRACKEDPERSON"
   "<TRACKEDPERSONS>"
   "TRACKEDPERSONS"
   "<DETECTEDPERSONS>"
   "DETECTEDPERSONS"
   "<DETECTEDPERSON>"
   "DETECTEDPERSON"
  ))

