// Generated by gencpp from file ppl_detection/Human.msg
// DO NOT EDIT!


#ifndef PPL_DETECTION_MESSAGE_HUMAN_H
#define PPL_DETECTION_MESSAGE_HUMAN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ppl_detection
{
template <class ContainerAllocator>
struct Human_
{
  typedef Human_<ContainerAllocator> Type;

  Human_()
    : tracking_no(0)
    , pos_x(0.0)
    , pos_y(0.0)
    , pos_z(0.0)
    , distance(0.0)  {
    }
  Human_(const ContainerAllocator& _alloc)
    : tracking_no(0)
    , pos_x(0.0)
    , pos_y(0.0)
    , pos_z(0.0)
    , distance(0.0)  {
    }



   typedef int32_t _tracking_no_type;
  _tracking_no_type tracking_no;

   typedef float _pos_x_type;
  _pos_x_type pos_x;

   typedef float _pos_y_type;
  _pos_y_type pos_y;

   typedef float _pos_z_type;
  _pos_z_type pos_z;

   typedef float _distance_type;
  _distance_type distance;




  typedef boost::shared_ptr< ::ppl_detection::Human_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ppl_detection::Human_<ContainerAllocator> const> ConstPtr;

}; // struct Human_

typedef ::ppl_detection::Human_<std::allocator<void> > Human;

typedef boost::shared_ptr< ::ppl_detection::Human > HumanPtr;
typedef boost::shared_ptr< ::ppl_detection::Human const> HumanConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ppl_detection::Human_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ppl_detection::Human_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ppl_detection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'ppl_detection': ['/home/c3mx/robot/src/ppl_detection/msg'], 'visualization_msgs': ['/opt/ros/jade/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ppl_detection::Human_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ppl_detection::Human_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ppl_detection::Human_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ppl_detection::Human_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ppl_detection::Human_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ppl_detection::Human_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ppl_detection::Human_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6cb5260ec06aeaff8021eb127c0c79ac";
  }

  static const char* value(const ::ppl_detection::Human_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6cb5260ec06aeaffULL;
  static const uint64_t static_value2 = 0x8021eb127c0c79acULL;
};

template<class ContainerAllocator>
struct DataType< ::ppl_detection::Human_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ppl_detection/Human";
  }

  static const char* value(const ::ppl_detection::Human_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ppl_detection::Human_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 tracking_no\n\
float32 pos_x\n\
float32 pos_y\n\
float32 pos_z\n\
float32 distance\n\
";
  }

  static const char* value(const ::ppl_detection::Human_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ppl_detection::Human_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tracking_no);
      stream.next(m.pos_x);
      stream.next(m.pos_y);
      stream.next(m.pos_z);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Human_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ppl_detection::Human_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ppl_detection::Human_<ContainerAllocator>& v)
  {
    s << indent << "tracking_no: ";
    Printer<int32_t>::stream(s, indent + "  ", v.tracking_no);
    s << indent << "pos_x: ";
    Printer<float>::stream(s, indent + "  ", v.pos_x);
    s << indent << "pos_y: ";
    Printer<float>::stream(s, indent + "  ", v.pos_y);
    s << indent << "pos_z: ";
    Printer<float>::stream(s, indent + "  ", v.pos_z);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PPL_DETECTION_MESSAGE_HUMAN_H
