// Generated by gencpp from file ppl_detection/Tracker.msg
// DO NOT EDIT!


#ifndef PPL_DETECTION_MESSAGE_TRACKER_H
#define PPL_DETECTION_MESSAGE_TRACKER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ppl_detection/Human.h>

namespace ppl_detection
{
template <class ContainerAllocator>
struct Tracker_
{
  typedef Tracker_<ContainerAllocator> Type;

  Tracker_()
    : header()
    , human()  {
    }
  Tracker_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , human(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::ppl_detection::Human_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::ppl_detection::Human_<ContainerAllocator> >::other >  _human_type;
  _human_type human;




  typedef boost::shared_ptr< ::ppl_detection::Tracker_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ppl_detection::Tracker_<ContainerAllocator> const> ConstPtr;

}; // struct Tracker_

typedef ::ppl_detection::Tracker_<std::allocator<void> > Tracker;

typedef boost::shared_ptr< ::ppl_detection::Tracker > TrackerPtr;
typedef boost::shared_ptr< ::ppl_detection::Tracker const> TrackerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ppl_detection::Tracker_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ppl_detection::Tracker_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ppl_detection

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'ppl_detection': ['/home/c3mx/robot/src/ppl_detection/msg'], 'visualization_msgs': ['/opt/ros/jade/share/visualization_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ppl_detection::Tracker_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ppl_detection::Tracker_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ppl_detection::Tracker_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ppl_detection::Tracker_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ppl_detection::Tracker_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ppl_detection::Tracker_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ppl_detection::Tracker_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ddcc20a6bcdf88fc6a57af1ba99d938";
  }

  static const char* value(const ::ppl_detection::Tracker_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ddcc20a6bcdf88fULL;
  static const uint64_t static_value2 = 0xc6a57af1ba99d938ULL;
};

template<class ContainerAllocator>
struct DataType< ::ppl_detection::Tracker_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ppl_detection/Tracker";
  }

  static const char* value(const ::ppl_detection::Tracker_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ppl_detection::Tracker_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
Human[] human\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: ppl_detection/Human\n\
int32 tracking_no\n\
float32 pos_x\n\
float32 pos_y\n\
float32 pos_z\n\
float32 distance\n\
";
  }

  static const char* value(const ::ppl_detection::Tracker_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ppl_detection::Tracker_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.human);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Tracker_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ppl_detection::Tracker_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ppl_detection::Tracker_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "human[]" << std::endl;
    for (size_t i = 0; i < v.human.size(); ++i)
    {
      s << indent << "  human[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ppl_detection::Human_<ContainerAllocator> >::stream(s, indent + "    ", v.human[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PPL_DETECTION_MESSAGE_TRACKER_H
