# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ppl_detection/Human.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Human(genpy.Message):
  _md5sum = "6cb5260ec06aeaff8021eb127c0c79ac"
  _type = "ppl_detection/Human"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 tracking_no
float32 pos_x
float32 pos_y
float32 pos_z
float32 distance

"""
  __slots__ = ['tracking_no','pos_x','pos_y','pos_z','distance']
  _slot_types = ['int32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       tracking_no,pos_x,pos_y,pos_z,distance

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Human, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.tracking_no is None:
        self.tracking_no = 0
      if self.pos_x is None:
        self.pos_x = 0.
      if self.pos_y is None:
        self.pos_y = 0.
      if self.pos_z is None:
        self.pos_z = 0.
      if self.distance is None:
        self.distance = 0.
    else:
      self.tracking_no = 0
      self.pos_x = 0.
      self.pos_y = 0.
      self.pos_z = 0.
      self.distance = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_i4f.pack(_x.tracking_no, _x.pos_x, _x.pos_y, _x.pos_z, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.tracking_no, _x.pos_x, _x.pos_y, _x.pos_z, _x.distance,) = _struct_i4f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_i4f.pack(_x.tracking_no, _x.pos_x, _x.pos_y, _x.pos_z, _x.distance))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.tracking_no, _x.pos_x, _x.pos_y, _x.pos_z, _x.distance,) = _struct_i4f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i4f = struct.Struct("<i4f")
